### ISSUE TITLE
Simplebot stuck on init

### ISSUE THREAD

**Issue by genya1** [SimpleBot-Inc/simplebot#62]
I have installed deltachat-core-rust with the python bindings, I can run `simplebot --version` successfully. But when I run:
```
simplebot init ADDR PASSWORD
```
with a email and password I created for the bot the command line is just stuck reporting this when I hit Crtl+C:
```
venv) $ simplebot --stdlog debug init ADDR PASSWORD
2021-03-03 11:20:39,698 - simplebot - DEBUG - registering plugin 'commands'
2021-03-03 11:20:39,700 - simplebot - DEBUG - registering plugin 'filters'
2021-03-03 11:20:39,702 - simplebot - DEBUG - registering plugin 'db'
2021-03-03 11:20:39,704 - simplebot - DEBUG - registered new command '/help'
2021-03-03 11:20:39,704 - simplebot - DEBUG - registered new command '/set'
2021-03-03 11:20:39,704 - simplebot - DEBUG - registered new command '/ban'
2021-03-03 11:20:39,705 - simplebot - DEBUG - registered new command '/unban'
^CTraceback (most recent call last):
  File "venv/bin/simplebot", line 10, in <module>
    sys.exit(main())
  File "venv/lib/python3.7/site-packages/simplebot/main.py", line 24, in main
    parser.main_run(bot=bot, args=args)
  File "venv/lib/python3.7/site-packages/simplebot/parser.py", line 88, in main_run
    res = args.subcommand_instance.run(bot=bot, args=args, out=out)
  File "venv/lib/python3.7/site-packages/simplebot/builtin/cmdline.py", line 51, in run
    args.emailaddr, args.password)
  File "venv/lib/python3.7/site-packages/simplebot/bot.py", line 248, in perform_configure_address
    configtracker.wait_finish()
  File "deltachat-core-rust/python/src/deltachat/tracker.py", line 98, in wait_finish
    if not self._configure_events.get():
  File "/usr/lib/python3.7/queue.py", line 170, in get
    self.not_empty.wait()
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
```

I think I installed something incorrectly or how long does the init process take ?

**Comment by genya1** [comment]
Figured out that it was stuck because the email server I use had custom email properties, was able to manually set the needed email server / port / security. Will make a new issue to work on creating a config file maybe for all the email properties.

This is really great, I like deltachat and the bot, thank you!
